version: '3'
services:
  web:
    container_name: fullstack-challenge-20230720
    image: fullstack-challenge-20230720
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/